name: 'tests'
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  js-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test
